### ISSUE TITLE
Running VART and Vitis-AI-Libray examples

### ISSUE THREAD

**Issue by Nunigan** [Xilinx/vck190-base-trd#3]
Hi
I Implemented the XVDPU overlay and the smart-mipi-app works.
I see that Vitis AI is installed on the image.
Is there a way to run the standard examples from VART or the Vitis-AI-Libray?
I understand that for the VCK190 and Vitis-AI the supported Image is still 2020.2. but this image is based on 2021.1 and the smart-mipi-app works.

Thanks, Michael

**Comment by chkohn** [comment]
@Nunigan I need to pull in some other folks to answer this. Will get back to you.

**Comment by yangyecs** [comment]
@Nunigan it depends on which type you are going to run. Samples support running with performance mode(command -line, without display), video file as input mode(need display output). If you are going to run examples with video mode, the short answer is no. The reason is video output implemented by calling OpenCV imshow(), which requires Xorg/Xwindow as backend by default, but it doest not support in this project. If you are going to run performance mode,  you can directly follow guider in [Vitis-AI](https://github.com/Xilinx/Vitis-AI) to run.  
Btw, Vtisi-AI 1.4.1 will be upload by tomorrow, which will support VCK190 with 2021.1 version. You can run all standard examples with  Vtisi-AI 1.4.1 image

**Comment by Nunigan** [comment]
@yangyecs Thank you for the Answer. That is great news with Vitis-AI 1.4.1.

The idea of the smart-mipi-app in this project is very promising and in the long run exactly what I need (with a different network though). 
Therefore a more detailed documentation or even a tutorial about how to build such an app and how to deploy the xvdpu would be highly appreciated!

Thanks a lot, Michael

**Comment by Nunigan** [comment]
@yangyecs as an addition to your answer regarding performance mode:

Primary there is the problem with shared libraries.

._/test_performance_facedetect densebox_320_320 test_performance_facedetect.list -t 8 -s 60
./test_performance_facedetect: error while loading shared libraries: libjson-c.so.4: cannot open shared object file: No such file or directory_

whereas libjson-c.so.5 is present in /usr/lib but not libjson-c.so.4, I guess thats the update between Petalinux 2020.2 and 2021.1
